[project]
name = "password-game-youtube-link"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "isodate>=0.7.2",
    "requests>=2.32.4",
]
